apiVersion: batch/v1
kind: Job
metadata:
  name: p1-exp1a-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: p1-exp1a
          image: clodu/p1-experiments:latest
          command: ["python", "scripts/p1/train_exp1a.py"]
          resources:
            limits:
              nvidia.com/gpu: 1
              cpu: "8"
              memory: "32Gi"
